# from http://jekyllrb.com/docs/continuous-integration/
language: ruby
rvm:
- 2.1
- 2.2
install: gem install jekyll rdiscount pygments.rb
script: jekyll build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer