# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.stevenwade.co.uk/
baseurl: /
title: Steven Wade
author: Steven Wade
description: Personal blog and resume
avatar: profile.jpg
email: steven@stevenwade.co.uk
github: swade1987 # username
twitter: swade1987
linkedin: stevendavidwade
disqus: swade1987
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
