# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Steven Wade
tagline:          'Design | Develop | Deploy'
description:      'Technical Consultant @ Parliamentary Digital Service. Coffee addict who is big on Continuous Delivery & DevOps. Made by <a href="https://twitter.com/swade1987" target="_blank">@swade1987</a>.'
url:              http://www.stevenwade.co.uk
baseurl:          /

author:
  name:           'Steven Wade'
  url:            https://twitter.com/swade1987

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/swade1987/swade1987.github.io
