baseURL = "https://www.stevenwade.co.uk"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Steve Wade"
theme = "hallo"
pygmentsCodefences  = true
pygmentsUseClasses  = true
enableGitInfo = true
enableRobotsTXT = true
rssLimit = 10  # Maximum number of items in the RSS feed.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
disqusShortname = "www-stevenwade-co-uk"

[author]
  name = "Steve Wade"

[params]
  gitUrl = "https://github.com/swade1987/swade1987.github.io/commit/"
  justifyContent = false
  themeVariant = "red"

  # Social Icons - Check https://fontawesome.com/icons?d=gallery for more info.
  [[params.links]]
    icon = "linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/stevendavidwade/"

  [[params.links]]
    icon = "github"
    title = "GitHub"
    url = "https://github.com/swade1987"

  [[params.links]]
    icon = "twitter"
    title = "Twitter"
    url = "https://twitter.com/swade1987"

  [[params.links]]
    icon = "medium"
    title = "Medium"
    url = "https://medium.com/@swade1987"

  [[params.links]]
    iconset = "fas"
    icon = "envelope"
    title = "E-mail"
    url = "mailto:steven@stevenwade.co.uk"

  [params.colors]
    background = "#326DE6"