baseURL = "https://www.stevenwade.co.uk"
title = "Steve Wade"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "www-stevenwade-co-uk"

[params]
    author = "Steve Wade"
    info = "Independent Kubernetes Consultant & Trainer"
    description = "Currently Platform Lead at Mettle in London"
    avatarurl = "images/portrait.jpg"
    hidecopyright = true
    hidecredits = true
    rtl = false
    colorscheme = "auto"

# Social Icons - Check https://fontawesome.com/icons?d=gallery for more info.
[[params.social]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/stevendavidwade/"

[[params.social]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/swade1987"

[[params.social]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/swade1987"

[[params.social]]
    icon = "fab fa-medium"
    title = "Medium"
    url = "https://medium.com/@swade1987"