version: '2'
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  web:
    build: .
    volumes:
       - .:/src
       - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000"
    labels:
      - "traefik.backend=jekyll"
      - "traefik.frontend.rule=Host:jekyll.docker.localhost"
