[build]
publish = "public"
command = "hugo --gc --minify"

# Production context: All deploys to the main epository branch will inherit these settings.
[context.production]
  command = "hugo --gc --minify"

# Deploy Preview context: All Deploy Previews will inherit these settings.
[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
